[mcp_servers.asaas]
url = "https://docs.asaas.com/mcp"

[mcp_servers.shadcn]
command = "npx"
args = [
    "shadcn@latest",
    "mcp",
]

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=wcnxwdcoambpfwxwubka&features=docs%2Caccount%2Cdatabase%2Cdebugging%2Cdevelopment%2Cfunctions%2Cbranching%2Cstorage"

[mcp_servers.vercel]
url = "https://mcp.vercel.com"

[mcp_servers.Sentry]
url = "https://mcp.sentry.dev/mcp/corretor-studio/sentry-camel-flower"

[mcp_servers.obsidian]
command = "npx"
args = [
    "-y",
    "@bitbonsai/mcpvault",
    "/run/media/matheuswillock/Armazenamento/Workspace´s Matheus Willock",
]
