/**
 * Reads the fixed backup CSVs and generates a Supabase migration SQL file
 * that restores the `functions` column in corretor_studio_team_members
 * and corretor_studio_profiles from the pre-migration backup.
 *
 * Only rows where functions is currently NULL or '{}' in the target table
 * are updated (idempotent).
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const FIXED_DIR = 'C:\\Users\\mathe\\Downloads\\backup\\fixed';
const TEAM_MEMBERS_CSV = join(FIXED_DIR, 'team_members_rows.csv');
const PROFILES_CSV = join(FIXED_DIR, 'profiles_rows.csv');

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let fields: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    const next = i + 1 < text.length ? text[i + 1] : '';

    if (c === '"') {
      if (inQuotes && next === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (c === ',' && !inQuotes) {
      fields.push(current);
      current = '';
    } else if ((c === '\r' || c === '\n') && !inQuotes) {
      if (c === '\r' && next === '\n') i++;
      fields.push(current);
      current = '';
      if (fields.length > 1 || fields[0] !== '') rows.push(fields);
      fields = [];
    } else {
      current += c;
    }
  }
  fields.push(current);
  if (fields.length > 1 || fields[0] !== '') rows.push(fields);
  return rows;
}

function escapeSqlLiteral(v: string): string {
  return v.replace(/'/g, "''");
}

/** Converts Postgres array literal e.g. {SDR,CLOSER} → '{SDR,CLOSER}'::"UserFunction"[] */
function toArrayLiteral(raw: string): string {
  const cleaned = raw.replace(/^\{/, '').replace(/\}$/, '').trim();
  if (!cleaned) return `'{}'::"UserFunction"[]`;
  const items = cleaned.split(',').map((s) => escapeSqlLiteral(s.trim()));
  return `'{${items.join(',')}}'::\"UserFunction\"[]`;
}

function buildTeamMemberInserts(rows: string[][], headers: string[]): string[] {
  const idIdx = headers.indexOf('id');
  const funcIdx = headers.indexOf('functions');

  const inserts: string[] = [];
  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    const id = row[idIdx]?.trim();
    const funcs = row[funcIdx]?.trim();
    if (!id) continue;
    inserts.push(`('${escapeSqlLiteral(id)}'::uuid, ${toArrayLiteral(funcs ?? '')})`);
  }
  return inserts;
}

function buildProfileInserts(rows: string[][], headers: string[]): string[] {
  const idIdx = headers.indexOf('id');
  const funcIdx = headers.indexOf('functions');

  const inserts: string[] = [];
  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    const id = row[idIdx]?.trim();
    const funcs = row[funcIdx]?.trim();
    if (!id) continue;
    inserts.push(`('${escapeSqlLiteral(id)}'::uuid, ${toArrayLiteral(funcs ?? '')})`);
  }
  return inserts;
}

const tmRows = parseCsv(readFileSync(TEAM_MEMBERS_CSV, 'utf-8'));
const tmHeaders = tmRows[0].map((h) => h.trim());
const tmInserts = buildTeamMemberInserts(tmRows, tmHeaders);

const profRows = parseCsv(readFileSync(PROFILES_CSV, 'utf-8'));
const profHeaders = profRows[0].map((h) => h.trim());
const profInserts = buildProfileInserts(profRows, profHeaders);

const sql = `-- Restores the \`functions\` column lost during the corretor_studio_* table rename migration.
-- Idempotent: only updates rows where functions IS NULL or '{}'.
-- Generated by scripts/generate-restore-functions-migration.ts on ${new Date().toISOString()}.

-- ─── team_members ──────────────────────────────────────────────────────────
do $$
declare
  _updated int;
begin
  create temp table if not exists _restore_tm_functions (
    id uuid,
    functions "UserFunction"[]
  ) on commit drop;

  insert into _restore_tm_functions (id, functions) values
${tmInserts.map((v) => `  ${v}`).join(',\n')}
  on conflict do nothing;

  update public.corretor_studio_team_members tm
  set functions = s.functions
  from _restore_tm_functions s
  where s.id = tm.id
    and (tm.functions is null or tm.functions = '{}');

  get diagnostics _updated = row_count;
  raise notice 'corretor_studio_team_members: % rows updated', _updated;
end $$;

-- ─── profiles ──────────────────────────────────────────────────────────────
do $$
declare
  _updated int;
begin
  create temp table if not exists _restore_profile_functions (
    id uuid,
    functions "UserFunction"[]
  ) on commit drop;

  insert into _restore_profile_functions (id, functions) values
${profInserts.map((v) => `  ${v}`).join(',\n')}
  on conflict do nothing;

  update public.corretor_studio_profiles p
  set functions = s.functions
  from _restore_profile_functions s
  where s.id = p.id
    and (p.functions is null or p.functions = '{}');

  get diagnostics _updated = row_count;
  raise notice 'corretor_studio_profiles: % rows updated', _updated;
end $$;
`;

// Determine next migration timestamp
const timestamp = new Date()
  .toISOString()
  .replace(/[-T:]/g, '')
  .replace(/\.\d+Z$/, '');

const migrationName = `${timestamp}_restore_team_member_and_profile_functions.sql`;
const migrationPath = join('supabase', 'migrations', migrationName);

writeFileSync(migrationPath, sql, 'utf-8');
console.info(`Migration written to ${migrationPath}`);
console.info(`  team_members rows to restore: ${tmInserts.length}`);
console.info(`  profiles rows to restore:     ${profInserts.length}`);
