-- Generated by `bun run db:migrate:from-prisma -- public-form-event-envelope-v1`.
-- The CLI also detected unrelated schema drift; only this migration's reviewed diff is retained.

alter type "public"."public_form_queue_event_kind" rename to "public_form_queue_event_kind__old_version_to_be_dropped";
create type "public"."public_form_queue_event_kind" as enum ('metric', 'progress', 'submission');
alter table "public"."corretor_studio_public_form_queue_event_failures"
  alter column "kind" type "public"."public_form_queue_event_kind"
  using "kind"::text::"public"."public_form_queue_event_kind";
drop type "public"."public_form_queue_event_kind__old_version_to_be_dropped";

alter table "public"."corretor_studio_public_form_answers"
  add column if not exists "answeredAt" timestamp(6) with time zone,
  add column if not exists "mappingKey" text,
  add column if not exists "sourceEventId" uuid;

alter table "public"."corretor_studio_public_form_metric_events"
  add column if not exists "eventId" uuid,
  add column if not exists "occurredAt" timestamp(6) with time zone,
  add column if not exists "schemaVersion" integer;

alter table "public"."corretor_studio_public_form_queue_event_failures"
  add column if not exists "eventId" uuid,
  add column if not exists "failureStage" text,
  add column if not exists "lastErrorCode" text,
  add column if not exists "schemaVersion" integer,
  add column if not exists "topic" text;

alter table "public"."corretor_studio_public_form_submissions"
  add column if not exists "dispatchAcceptedAt" timestamp(6) with time zone,
  add column if not exists "dispatchAttemptCount" integer not null default 0,
  add column if not exists "eventId" uuid,
  add column if not exists "lastDispatchError" text,
  add column if not exists "nextDispatchAt" timestamp(6) with time zone;

create index if not exists "corretor_studio_public_form_metric_events_eventId_idx"
  on "public"."corretor_studio_public_form_metric_events" ("eventId");
create index if not exists "corretor_studio_public_form_queue_event_failures_eventId_idx"
  on "public"."corretor_studio_public_form_queue_event_failures" ("eventId");
create index if not exists "corretor_studio_public_form_submissions_status_nextDispatch_idx"
  on "public"."corretor_studio_public_form_submissions" ("status", "nextDispatchAt");
