-- Generated by `bun run db:migrate:from-prisma -- public-form-submission-dispatch-context`.
-- The CLI also detected unrelated schema drift; only this migration's reviewed diff is retained.
-- Persists the dispatch context (thank-you page + requested meeting) so submission
-- recovery can rebuild the background job without losing scheduling data.

alter table "public"."corretor_studio_public_form_submissions"
  add column if not exists "thankYouPageId" uuid,
  add column if not exists "scheduledMeetingStartsAt" timestamp(6) with time zone;
