export const FEATURE_SLUGS = {
  CRM: "crm",
  CRM_LEAD_TRANSFERS: "crm-lead-transfers",
  CRM_DASHBOARD: "crm-dashboard",
  CRM_CALENDAR: "crm-calendar",
  CRM_PERFORMANCE: "crm-performance",
  CRM_SIMULATOR: "crm-simulator",
  CRM_TIME: "crm-time",
  CRM_TIME_MANAGE_TEAMS: "crm-time-manage-teams",
  CRM_TIME_MANAGE_USERS: "crm-time-manage-users",
  CRM_WALLET: "crm-wallet",
  EMAIL: "email",
  EMAIL_TEMPLATES: "email-templates",
  EMAIL_CONTACTS: "email-contacts",
  EMAIL_CAMPAIGNS: "email-campaigns",
  EMAIL_HISTORY: "email-history",
  EMAIL_ANALYTICS: "email-analytics",
  EMAIL_SETTINGS: "email-settings",
  CONFIGURATION: "integration",
  WHATSAPP: "whatsapp",
  WHATSAPP_SETTINGS: "whatsapp-settings",
  WHATSAPP_AUTO_RESPONSES: "whatsapp-auto-responses",
  CDP: "cdp",
} as const

export type FeatureSlug = (typeof FEATURE_SLUGS)[keyof typeof FEATURE_SLUGS]
