export const operatorsData = [
  "Amil",
  "Benevida",
  "Bradesco",
  "Hapvida",
  "MedSênior",
  "NotreDame Intermédica (GNDI)",
  "Omint",
  "Plena",
  "Porto Seguro",
  "Prevent Senior",
  "Santa Casa",
  "Sermed",
  "SulAmérica",
  "Unimed",
]
